### ISSUE TITLE
dwarf_step doesnt pick up CIE-only FDE

### ISSUE THREAD

**Issue by RYDB3RG** [libunwind/libunwind#285]
Hi,

I have an FDE that looks like this:

```
00208b40 00000014 00208b44 FDE cie=00000000 pc=00fd43f0...00fd4400
  Format:       DWARF32
  DW_CFA_nop:
  DW_CFA_nop:
  DW_CFA_nop:
  DW_CFA_nop:
  DW_CFA_nop:
  DW_CFA_nop:
  DW_CFA_nop:

  0xfd43f0: CFA=RSP+8: RIP=[CFA-8]
```

this is the corresponding asm (intel syntax):
```
  fd43f0:	48 89 f2             	mov    rdx,rsi
  fd43f3:	48 89 fe             	mov    rsi,rdi
  fd43f6:	bf 01 00 00 00       	mov    edi,0x1
  fd43fb:	e9 c0 ff 22 ff       	jmp    2043c0
```

The problem is that libunwind falls back to frame-chain when resolving `fd43f0`:
```
>_Ux86_64_step: (cursor=0x7ffff6272590, ip=0x00007fffd66f93f0, cfa=0x00007fffffffd8c8)
            >_UPT_get_dyn_info_list_addr: looking for dyn_info list
             >_Ux86_64_step: dwarf_step() failed (ret=-10), trying frame-chain
                >_UPT_access_mem: mem[7fffd66f93f0] -> 1bffe8948f28948
                >_UPT_access_mem: mem[7fffd66f93f8] -> ff22ffc0e9000000
              >is_plt_entry: ip=0x7fffd66f93f0 => 0x01bffe8948f28948 0xff22ffc0e9000000, ret = 0
                >_UPT_access_reg: using getregset: reg: RBP [6], val: 7ffff626f028, write: 0
                >_UPT_access_mem: mem[7fffd66f93f0] -> 1bffe8948f28948
  >_Ux86_64_step: RIP fixup didn't work, falling back
                >_UPT_access_mem: mem[7fffffffd8e0] -> 7fffffffd910
 >_Ux86_64_step: [RBP=0x6] = 0x7fffffffd8e0 (cfa = 0x7fffffffd8c8) -> 0x7fffffffd910
                >_UPT_access_mem: mem[7fffffffd8e8] -> 7fffd6630b72
 >_Ux86_64_step: Frame Chain [RIP=0x7fffffffd8e8] = 0x7fffd6630b72
  >_Ux86_64_step: returning 1
```

In my case, this misses a tail-call frame. I'm wondering if its caused by the FDE being NOP-only.
